use std::fmt::Display;

#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum Delim {
    Open,
    Close,
}

#[derive(Clone, Debug, PartialEq)]
pub enum Token {
    Ident(String),

    Integer(u64),
    Float(f64),
    String(String),

    /* control tokens */
    Newline,
    Indent,
    Dedent,
    Eof,

    /* keywords */
    As,
    Fn,
    Let,
    If,
    Impl,
    Else,
    Enum,
    For,
    Match,
    Mut,
    Mod,
    Use,
    Null,
    Loop,
    Where,
    SelfLower,
    SelfUpper,
    Struct,
    Trait,
    True,
    False,
    Void,
    Bool,
    Pub,
    U8,
    U16,
    U32,
    U64,
    U128,
    Usize,
    I8,
    I16,
    I32,
    I64,
    I128,
    Isize,
    F32,
    F64,

    /* triple-character symbols */
    DotDotDot,

    /* double-character symbols */
    SlashSlash,
    FatArrow,
    Arrow,
    ColonColon,
    DotDot,
    EqEq,
    NotEq,
    LtEq,
    GtEq,
    AndAnd,
    OrOr,

    /* single-character symbols */
    Colon,
    Semi,
    Dot,
    Comma,
    Eq,
    Not,
    Lt,
    Gt,
    And,
    Or,
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Caret,
    Quote,
    Under,
    Paren(Delim),
    Brace(Delim),
    Bracket(Delim),
}

impl Token {
    pub fn from_keyword(keyword: &str) -> Option<Token> {
        match keyword {
            "as" => Some(Token::As),
            "fn" => Some(Token::Fn),
            "let" => Some(Token::Let),
            "if" => Some(Token::If),
            "impl" => Some(Token::Impl),
            "else" => Some(Token::Else),
            "enum" => Some(Token::Enum),
            "for" => Some(Token::For),
            "match" => Some(Token::Match),
            "mut" => Some(Token::Mut),
            "mod" => Some(Token::Mod),
            "use" => Some(Token::Use),
            "null" => Some(Token::Null),
            "loop" => Some(Token::Loop),
            "where" => Some(Token::Where),
            "struct" => Some(Token::Struct),
            "self" => Some(Token::SelfLower),
            "Self" => Some(Token::SelfUpper),
            "trait" => Some(Token::Trait),
            "true" => Some(Token::True),
            "false" => Some(Token::False),
            "void" => Some(Token::Void),
            "bool" => Some(Token::Bool),
            "pub" => Some(Token::Pub),
            "u8" => Some(Token::U8),
            "u16" => Some(Token::U16),
            "u32" => Some(Token::U32),
            "u64" => Some(Token::U64),
            "u128" => Some(Token::U128),
            "usize" => Some(Token::Usize),
            "i8" => Some(Token::I8),
            "i16" => Some(Token::I16),
            "i32" => Some(Token::I32),
            "i64" => Some(Token::I64),
            "i128" => Some(Token::I128),
            "isize" => Some(Token::Isize),
            "f32" => Some(Token::F32),
            "f64" => Some(Token::F64),
            _ => None,
        }
    }

    pub fn from_symbol(symbol: &str) -> Option<Token> {
        match symbol {
            /* triple-character symbols */
            "..." => Some(Token::DotDotDot),

            /* double-character symbols */
            "//" => Some(Token::SlashSlash),
            "=>" => Some(Token::FatArrow),
            "->" => Some(Token::Arrow),
            "::" => Some(Token::ColonColon),
            ".." => Some(Token::DotDot),
            "==" => Some(Token::EqEq),
            "!=" => Some(Token::NotEq),
            "<=" => Some(Token::LtEq),
            ">=" => Some(Token::GtEq),
            "&&" => Some(Token::AndAnd),
            "||" => Some(Token::OrOr),

            /* single-character symbols */
            ":" => Some(Token::Colon),
            ";" => Some(Token::Semi),
            "." => Some(Token::Dot),
            "," => Some(Token::Comma),
            "=" => Some(Token::Eq),
            "!" => Some(Token::Not),
            "<" => Some(Token::Lt),
            ">" => Some(Token::Gt),
            "&" => Some(Token::And),
            "|" => Some(Token::Or),
            "+" => Some(Token::Plus),
            "-" => Some(Token::Minus),
            "*" => Some(Token::Star),
            "/" => Some(Token::Slash),
            "%" => Some(Token::Percent),
            "^" => Some(Token::Caret),
            "'" => Some(Token::Quote),
            "_" => Some(Token::Under),
            "(" => Some(Token::Paren(Delim::Open)),
            ")" => Some(Token::Paren(Delim::Close)),
            "{" => Some(Token::Brace(Delim::Open)),
            "}" => Some(Token::Brace(Delim::Close)),
            "[" => Some(Token::Bracket(Delim::Open)),
            "]" => Some(Token::Bracket(Delim::Close)),
            _ => None,
        }
    }
}

impl Display for Token {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Token::Ident(ident) => write!(f, "{}", ident),
            Token::Integer(int) => write!(f, "{}", int),
            Token::Float(float) => write!(f, "{}", float),
            Token::String(string) => write!(f, "\"{}\"", string),
            /* control tokens */
            Token::Newline => write!(f, "newline"),
            Token::Indent => write!(f, "indent"),
            Token::Dedent => write!(f, "dedent"),
            Token::Eof => write!(f, "eof"),

            /* keywords */
            Token::As => write!(f, "as"),
            Token::Fn => write!(f, "fn"),
            Token::Let => write!(f, "let"),
            Token::If => write!(f, "if"),
            Token::Impl => write!(f, "impl"),
            Token::Else => write!(f, "else"),
            Token::Enum => write!(f, "enum"),
            Token::For => write!(f, "for"),
            Token::Match => write!(f, "match"),
            Token::Mut => write!(f, "mut"),
            Token::Mod => write!(f, "mod"),
            Token::Use => write!(f, "use"),
            Token::Null => write!(f, "null"),
            Token::Loop => write!(f, "loop"),
            Token::Where => write!(f, "where"),
            Token::Struct => write!(f, "struct"),
            Token::SelfLower => write!(f, "self"),
            Token::SelfUpper => write!(f, "Self"),
            Token::Trait => write!(f, "trait"),
            Token::True => write!(f, "true"),
            Token::False => write!(f, "false"),
            Token::Void => write!(f, "void"),
            Token::Bool => write!(f, "bool"),
            Token::Pub => write!(f, "pub"),
            Token::U8 => write!(f, "u8"),
            Token::U16 => write!(f, "u16"),
            Token::U32 => write!(f, "u32"),
            Token::U64 => write!(f, "u64"),
            Token::U128 => write!(f, "u128"),
            Token::Usize => write!(f, "usize"),
            Token::I8 => write!(f, "i8"),
            Token::I16 => write!(f, "i16"),
            Token::I32 => write!(f, "i32"),
            Token::I64 => write!(f, "i64"),
            Token::I128 => write!(f, "i128"),
            Token::Isize => write!(f, "isize"),
            Token::F32 => write!(f, "f32"),
            Token::F64 => write!(f, "f64"),

            /* triple-character symbols */
            Token::DotDotDot => write!(f, "..."),

            /* double-character symbols */
            Token::SlashSlash => write!(f, "//"),
            Token::FatArrow => write!(f, "=>"),
            Token::Arrow => write!(f, "->"),
            Token::ColonColon => write!(f, "::"),
            Token::DotDot => write!(f, ".."),
            Token::EqEq => write!(f, "=="),
            Token::NotEq => write!(f, "!="),
            Token::LtEq => write!(f, "<="),
            Token::GtEq => write!(f, ">="),
            Token::AndAnd => write!(f, "&&"),
            Token::OrOr => write!(f, "||"),

            /* single-character symbols */
            Token::Colon => write!(f, ":"),
            Token::Semi => write!(f, ";"),
            Token::Dot => write!(f, "."),
            Token::Comma => write!(f, ","),
            Token::Eq => write!(f, "="),
            Token::Not => write!(f, "!"),
            Token::Lt => write!(f, "<"),
            Token::Gt => write!(f, ">"),
            Token::And => write!(f, "&"),
            Token::Or => write!(f, "|"),
            Token::Plus => write!(f, "+"),
            Token::Minus => write!(f, "-"),
            Token::Star => write!(f, "*"),
            Token::Slash => write!(f, "/"),
            Token::Percent => write!(f, "%"),
            Token::Caret => write!(f, "^"),
            Token::Quote => write!(f, "'"),
            Token::Under => write!(f, "_"),
            Token::Paren(Delim::Open) => write!(f, "("),
            Token::Paren(Delim::Close) => write!(f, ")"),
            Token::Brace(Delim::Open) => write!(f, "{{"),
            Token::Brace(Delim::Close) => write!(f, "}}"),
            Token::Bracket(Delim::Open) => write!(f, "["),
            Token::Bracket(Delim::Close) => write!(f, "]"),
        }
    }
}
